import random, re
random.seed(42)

topics = [
    ('numpy', ['numpy arrays store homogeneous data in an N-dimensional grid and support vectorized operations.', 'Broadcasting automatically aligns arrays of different shapes for arithmetic by expanding dimensions.', 'You index arrays with arr[0] for scalars and arr[arr > 5] for boolean masking.', 'numpy dtypes like int32 and float64 specify the element type and smaller dtypes save memory.', 'Vectorized operations replace Python loops so np.mean(arr) computes the mean at once.', 'Boolean masks select elements where a condition is true like arr[arr % 2 == 0].', 'The np.where() function acts like a vectorized ternary replacing negatives with zero.', 'You can reshape arrays with arr.reshape(3, 4) and flatten them with arr.ravel().', 'Multi-dimensional arrays use comma-separated indices like arr[0, :] to get a row.', 'numpy.concatenate() joins arrays along an axis and np.hstack() combines horizontally.', 'You can extract diagonal elements using arr.diagonal() for the sum of diagonal values.', 'numpy.linalg provides linear algebra functions like inv() for matrix inversion.', 'The np.random module generates random arrays with functions like rand() and randn().', 'You can sort arrays using np.sort() or argsort() which returns the sort indices.', 'Horizontal stacking joins arrays side by side while vertical stacking adds rows.', 'The np.unique() function returns sorted unique elements and their inverse mapping.', 'numpy.save() and numpy.load() handle binary storage of arrays in the npy format.', 'The np.diff() function calculates the discrete difference along a given axis.', 'You can compute dot products with np.dot() or the @ operator for matrix multiplication.', 'numpy.ix_() constructs open mesh from multiple sequences enabling fancy indexing.', 'The np.flatnonzero() function returns indices of non-zero elements in flattened order.', 'Array broadcasting rules apply even when dimensions differ by one.', 'numpy.stack() creates a new axis by joining arrays along a fresh dimension.', 'The np.roll() function shifts elements along an axis wrapping around to the end.', 'numpy.percentile() computes the q-th percentile of data along the specified axis.', 'You can use np.where() with three arguments to select from two arrays based on a condition.', 'The np.nonzero() function returns indices of elements that are non-zero.', 'numpy.cumsum() returns the cumulative sum of array elements along a given axis.', 'The np.meshgrid() function creates coordinate matrices from coordinate vectors.', 'numpy.flip() reverses the order of elements along a specified axis.'],
    ('csv', ['The csv module reads comma-separated values with csv.reader() and writes with csv.writer().', 'sqlite3 provides an embedded SQL database where cur.execute() runs SQL commands.', 'Use parameterized queries like cur.execute("SELECT * FROM users WHERE name = ?", (name,)) to prevent SQL injection.', 'The with sqlite3.connect("db.db") as conn: statement auto-commits on exit and rolls back.', 'Use conn.row_factory = sqlite3.Row to get dict-like rows where you access columns by name.', 'For bulk inserts, executemany() runs the same statement with a list of tuples.', 'csv.Sniffer() detects the delimiter automatically from a sample.', 'You can query the last inserted row id with cur.lastrowid.', 'Use csv.QUOTE_ALL to wrap every field in quotes or csv.QUOTE_MINIMAL for the delimiter only.', 'sqlite3 supports CREATE TABLE, INSERT, SELECT, and DELETE queries.', 'csv.DictReader returns rows as dictionaries mapping field names to values.', 'The csv.writerow() method writes a single row and writerows() writes multiple rows.', 'You can register custom dialects with csv.register_dialect() for different formatting.', 'sqlite3.OperationalError indicates a problem with the SQL syntax or database.', 'The sqlite3.Connection.in_transaction property indicates whether a transaction is active.', 'You can use cursor.execute("DROP TABLE IF EXISTS tab") to safely remove a table.', 'csv.field_size_limit() returns or sets the maximum field size allowed by the parser.', 'sqlite3.Connection.iterdump() yields SQL statements to recreate the database.', 'You can use connection.execute() directly without creating a cursor for simple statements.', 'The csv module handles quoted fields where the delimiter appears inside quotes.', 'sqlite3.Connection.set_progress_handler() calls a callback periodically during long queries.', 'You can attach multiple databases with ATTACH DATABASE to query across separate files.', 'csv.QUOTE_NONNUMERIC forces all non-numeric fields to be quoted and converts numbers.', 'sqlite3.Connection.create_function() registers a custom SQL function written in Python.', 'You can use context managers with sqlite3 to automatically handle transaction commits.', 'The csv.writer() object takes a file-like object and a dialect parameter for formatting.', 'sqlite3.Row supports both index-based and key-based access to column values.', 'You can use the sqlite3.Connection.commit() method explicitly to save changes to disk.', 'csv.DictWriter requires a fieldnames argument that specifies the order of columns.', 'sqlite3.Connection.close() properly shuts down the database connection when done.']),
    ('sec', ['The statistics module provides mean(), median(), and stdev() for basic analysis on numeric data.', 'uuid.uuid4() generates a random UUID while uuid.uuid5() creates a deterministic one.', 'secrets.token_bytes(32) generates cryptographically secure random bytes for keys.', 'hashlib.sha256(data).hexdigest() computes a SHA-256 hash for integrity checks.', 'statistics.stdev() computes sample standard deviation using n-1 while pstdev() uses n.', 'secrets.token_urlsafe(16) produces a URL-safe random string for passwords.', 'hashlib.pbkdf2_hmac() derives cryptographic keys from passwords with iteration counts.', 'uuid.UUID(string) parses a UUID and raises ValueError if the format is invalid.', 'statistics.quantiles() splits data into quartiles useful for understanding distributions.', 'hmac.new(key, message, hashlib.sha256) computes a keyed hash verifying integrity.', 'The statistics.fmean() function computes a fast floating-point mean introduced in Python 3.8.', 'secrets.choice() selects a random element from a non-empty sequence securely.', 'hashlib.new() creates a hash object using a named algorithm like sha3_256.', 'uuid.getnode() returns the hardware address as a 48-bit integer used in MAC addresses.', 'statistics.mode() returns the most common data point for unimodal distributions.', 'secrets.compare_digest() securely compares two strings while avoiding timing attacks.', 'hashlib.md5() produces a 128-bit hash but is not recommended for security purposes.', 'uuid.UUID(int=...) constructs a UUID from a large integer representation.', 'statistics.geometric_mean() returns the geometric mean of positive data values.', 'hmac.digest() returns the digest of a message as bytes without the hex conversion.', 'The statistics.harmonic_mean() returns the reciprocal of the arithmetic mean of reciprocals.', 'secrets.token_hex(n) returns random text containing n random bytes in hexadecimal.', 'hashlib.blake2b() is a fast hash function that can serve as a keyed hash for authentication.', 'uuid.uuid1() generates a UUID from a host ID and current time.', 'statistics.pstdev() returns the population standard deviation of the entire data set.', 'secrets.randbits(k) returns an integer with k random bits useful for generating masks.', 'hashlib.sha1() produces a 160-bit hash but has known collision vulnerabilities.', 'uuid.NAMESPACE_URL and uuid.NAMESPACE_DNS are predefined namespaces for uuid5().', 'statistics.median_high() returns the high median for datasets with an odd number of points.', 'secrets.token_urlsafe(n) returns a random URL-safe text string with approximately n bytes.']),
    ('heap', ['bisect.bisect_left(sorted_list, x) finds the insertion point in O(log n) while bisect.insort() inserts while sorted.', 'heapq.heappush(heap, item) and heapq.heappop(heap) maintain a min-heap with the smallest at index 0.', 'heapq.nsmallest(3, data) finds the three smallest items without sorting the entire list.', 'heapq.merge(seq1, seq2) lazily merges sorted iterables into one sorted stream.', 'heapq.heapify(my_list) reorganizes an arbitrary list into a heap in O(n) time.', 'You can push tuples like heapq.heappush(pq, (priority, item)) so the heap orders by priority.', 'heapq.heapreplace() pops the smallest and pushes a new item in one O(log n) step.', 'bisect.insort() maintains sorted order when inserting into a list without a full re-sort.', 'A min-heap implements a priority queue where heappop() returns the lowest priority item.', 'heapq.nlargest() is faster than sorting when you only need a few extremes from a large collection.', 'heapq.heappushpop() pushes an item and then pops the smallest in one operation.', 'bisect.bisect_right() returns the insertion point after any existing entries of the same value.', 'The heapq module works with any comparable objects not just numbers as long as they support comparison.', 'bisect.insort_right() inserts an element after any existing entries maintaining sorted order.', 'heapq.heapify() is faster than repeatedly calling heappush because it runs in linear time.', 'You can use heapq with tuples where the first element is the priority and the rest is the data.', 'bisect works on any sorted sequence including lists of tuples as long as comparison is valid.', 'The heap property guarantees that the parent node is always less than or equal to its children.', 'heapq.nsmallest() with n equal to the list length is equivalent to calling sorted().', 'You can implement a max-heap by negating values before pushing them with heapq.heappush().', 'heapq.heappushpop() is more efficient than calling heappush and heappop separately.', 'bisect.bisect() is an alias for bisect.bisect_right() that returns the insertion index.', 'The heapq module provides heapreplace() which is faster than separate pop and push operations.', 'You can use heapq.nlargest() with a key function to customize the comparison logic.', 'bisect.insort_left() inserts before any existing entries of the same value.', 'The heapq module also provides heapify() which converts a list into a heap in place.', 'You can use heapq.nsmallest() and heapq.nlargest() with a key function for custom comparisons.']),
    ('coll', ['Counter from collections counts elements and most_common() ranks them by frequency.', 'defaultdict(int) supplies 0 for missing keys so counts[key] += 1 works without checking.', 'OrderedDict preserves insertion order with move_to_end() for reordering.', 'deque with maxlen=N automatically discards the oldest item when full.', 'collections.ChainMap groups multiple dicts as one layer where the first dict takes priority.', 'Counter supports arithmetic like Counter("ab") + Counter("bc") adding counts element-wise.', 'list(counter.elements()) expands a Counter back into a list repeating each element.', 'deque.appendleft() and deque.popleft() provide O(1) operations on both ends.', 'ChainMap.new_child() adds a new layer on top for merging config sources.', 'OrderedDict.move_to_end(key, last=False) moves a key to the front enabling LRU cache behavior.', 'Counter.subtract() decreases counts using negative values useful for finding differences.', 'defaultdict(list) creates a dictionary where each missing key gets an empty list as default.', 'deque.rotate() moves elements to the right or left in a circular fashion.', 'ChainMap.maps is a list of dictionaries representing each layer in order.', 'Counter.most_common() without arguments returns all elements sorted by count descending.', 'defaultdict(factory) calls the factory function only when a key is missing.', 'OrderedDict equality checks consider insertion order unlike regular dict comparison.', 'deque.clear() removes all elements from the deque in O(n) time.', 'collections.UserDict and UserList provide mutable wrappers around dict and list for subclassing.', 'ChainMap.new_child() can be called with an explicit mapping to prepend it as the first layer.', 'Counter.update() adds counts from an iterable or another counter to the current counts.', 'defaultdict(default_factory) creates a default value using the factory when a key is missing.', 'deque.append() adds to the right end while appendleft() adds to the left end.', 'OrderedDict.popitem(last=True) removes and returns the last or first item depending on the flag.', 'ChainMap.parents returns a new ChainMap with the first mapping removed from the layers.', 'Counter.elements() returns an iterator over elements repeating each as many times as its count.']),
    ('path', ['Path.glob finds files matching a pattern while Path.iterdir() lists immediate children.', 'Path.walk() yields dirpath, dirnames, and filenames for each directory like os.walk.', 'Path.home() returns the user home directory and Path.resolve() gives the absolute path.', 'Path.with_suffix replaces the file extension while with_name replaces the filename.', 'Path.stat() returns metadata including st_size for bytes and st_mtime for modification time.', 'Path.suffix gives the last extension and stem gives the name without the last suffix.', 'Path.rglob searches recursively while Path.mkdir creates nested directories.', 'Path.open() works like built-in open while read_text() provides convenient string I/O.', 'Path.samefile checks if two paths refer to the same file and is_symlink detects symlinks.', 'Path.parent gives the containing directory while parents[1] goes up another level.', 'Path.as_posix() returns the path as a string with forward slashes regardless of platform.', 'Path.chmod() changes the file permissions and Path.owner() returns the file owner name.', 'Path.is_file() returns True for regular files while Path.is_dir() returns True for directories.', 'Path.read_bytes() returns the file contents as bytes and read_text() decodes as a string.', 'Path.write_bytes() writes bytes to the file while write_text() accepts a string argument.', 'Path.lchmod() changes permissions on symbolic links themselves rather than their targets.', 'Path.touch() creates an empty file if it does not exist or updates the modification time.', 'Path.unlink() removes a file or symbolic link while rmdir() removes an empty directory.', 'Path.expanduser() replaces the ~ prefix with the user home directory path.', 'Path.absolute() returns the absolute path without resolving symlinks unlike resolve().', 'Path.with_stem() replaces the stem part of the filename while keeping the suffix.', 'Path.link_to() creates a hard link pointing to the same file as the original path.', 'Path.exists() returns True if the path points to an existing file or directory.', 'Path.readonly() and Path.writeable() indicate whether the path has read or write permissions.', 'Path.mkdir() creates a directory and parents=True creates any missing intermediate directories.', 'Path.with_suffix() can be chained with with_name() for full renaming like p.with_name("x").with_suffix("txt").']),
]

topic_labels = ['numpy arrays and broadcasting', 'csv and sqlite3 database modules', 'statistics, uuid, secrets, and hashlib', 'bisect and heapq priority queues', 'collections Counter, defaultdict, OrderedDict, and deque', 'pathlib Path methods, glob, and walk']

first_q = ['what is {name}', 'can you explain {name}', 'how do i use {name} in Python', 'what does {name} do', 'how does {name} work', 'what are the main features of {name}', 'tell me about {name}', 'how would i get started with {name}', 'what is the purpose of {name}', 'how do i implement {name}']
fu_q = ['how does this compare to the standard approach', 'what if i need to handle multiple values at once', 'can this be combined with other techniques', 'what happens when the data grows very large', 'how do i adapt this for a different scenario', 'does this work with nested structures', 'what are the performance tradeoffs', 'how do i know when to pick this', 'can this work alongside exception handling', 'what if i need to customize the behavior', 'how does this scale with larger inputs', 'what edge cases should i watch for', 'does this maintain the original order', 'what would i do if this raised an error', 'how do i thread this with concurrent code']

blocks = []

for i in range(80):
    ti = random.randrange(len(topics))
    key, answers, label = topics[ti]
    num_select = min(4, len(answers))
    selected = random.sample(answers, num_select)
    num_turns = random.randint(2, num_select)
    block = [f'User: {random.choice(first_q).format(name=label)}']
    block.append(f'Joe: {selected[0]}')
    for j in range(1, num_turns):
        block.append(f'User: {random.choice(fu_q)}')
        block.append(f'Joe: {selected[j]}')
    blocks.append(block)

for i in range(50):
    ti = random.randrange(len(topics))
    key, answers, label = topics[ti]
    ans = random.choice(answers)
    blocks.append([f'User: {random.choice(first_q).format(name=label)}', f'Joe: {ans}'])

random.shuffle(blocks)
multi = sum(1 for b in blocks if len(b) >= 4)
print(f'Total: {len(blocks)}, Multi: {multi} ({multi/len(blocks)*100:.1f}%)')

bad = 0
for i, b in enumerate(blocks):
    for line in b:
        if line.startswith('Joe: '):
            ans = line[5:]
            sents = len(re.findall(r'[.!?](?:\s|$)', ans))
            if sents > 3:
                bad += 1
    if not b[0].startswith('User: '):
        bad += 1
print(f'Format/sentence issues: {bad}')

content = '\n\n'.join(['\n'.join(b) for b in blocks]) + '\n'
non_ascii = sum(1 for c in content if ord(c) > 127)
print(f'Non-ASCII: {non_ascii}, Backticks: {content.count(chr(96))}')
print(f'Blocks: {len(blocks)}, Blank separators: {content.count(chr(10)+chr(10))}')

output = '\n\n'.join(['\n'.join(b) for b in blocks]) + '\n'
with open('/Users/dev/github-projects/joe-brain/data/_gen/python/python_mt_09_cand.txt', 'w') as f:
    f.write(output)
print('Written!')
