import os
import random

random.seed(42)

pairs = [
    # Basics
    ("What is a tree?", "A tree is a perennial plant with an elongated stem, or trunk, supporting branches and leaves. Trees typically live for many years and can grow tall, using their height to access sunlight above other plants."),
    ("What are the main parts of a tree?", "The main parts of a tree are the roots, trunk, branches, leaves, and sometimes flowers and fruits. The roots anchor the tree and absorb water, the trunk supports the canopy, and the leaves perform photosynthesis."),
    ("What does a tree need to grow?", "A tree needs sunlight, water, carbon dioxide, and nutrients from the soil. Sunlight drives photosynthesis, water transports nutrients, and carbon dioxide is converted into sugars the tree uses for energy and growth."),
    ("How do trees make food?", "Trees make food through photosynthesis. Chlorophyll in the leaves captures sunlight and uses its energy to combine carbon dioxide and water into glucose, releasing oxygen as a byproduct."),
    ("What is photosynthesis in a tree?", "Photosynthesis is the process where a tree uses sunlight, water, and carbon dioxide to produce glucose for food and release oxygen. It happens mainly in the leaves where chlorophyll captures light energy."),
    ("Where does a tree get its carbon?", "A tree gets most of its carbon from carbon dioxide in the air, not from the soil. During photosynthesis the tree converts CO2 into sugars that build cellulose and lignin, which make up its wood."),
    ("What is the trunk of a tree?", "The trunk is the main stem of the tree that supports branches and leaves. It transports water upward through the xylem and sugars downward through the phloem, and its rings record the tree's yearly growth."),
    ("Why do trees have bark?", "Bark protects the tree from weather, insects, and disease. It is made of dead outer cells that shield the living phloem and cambium underneath, and it can also help insulate the tree from fire and cold."),
    ("What are roots for?", "Roots anchor the tree in the soil and absorb water and minerals. A tree's roots often spread as wide as its canopy, and the fine root hairs near the tips do most of the water uptake."),
    ("What is the canopy?", "The canopy is the upper layer of branches and leaves of a tree. It is where most photosynthesis happens and provides shade, habitat, and a place for birds and insects to live."),
    # Tree rings / growth
    ("How can you tell a tree's age?", "You can estimate a tree's age by counting the rings on a cross-section of its trunk. Each year the tree adds one growth ring, and the width of a ring indicates how good that year's growing conditions were."),
    ("What are tree rings?", "Tree rings are the concentric circles visible in a cut trunk. Each ring represents one year of growth, with a light early-wood band and a darker late-wood band, and their patterns show climate history."),
    ("Do all trees grow one ring per year?", "Most trees in areas with distinct seasons grow one ring per year, so rings count the years. In tropical regions without seasons, rings may be faint, irregular, or not clearly annual."),
    ("What is the cambium?", "The cambium is the thin layer of living cells just under the bark that produces new xylem and phloem. As the cambium divides, it adds a new layer of wood each year, thickening the trunk."),
    ("What is heartwood?", "Heartwood is the dark, dense, dead wood at the center of the trunk. It no longer transports water but provides structural support and is often more resistant to decay than the living sapwood around it."),
    ("What is sapwood?", "Sapwood is the younger, lighter outer layer of wood that still transports water upward. It is softer and more active than heartwood and gradually becomes heartwood as the tree ages."),
    ("Why do some trees grow faster than others?", "Growth speed depends on sunlight, water, nutrients, genetics, and species. Fast growers like willows and poplars make soft, quick wood, while slow growers like oaks produce dense, durable wood."),
    ("What is a growth ring made of?", "Each growth ring is made of a light earlywood band formed in spring when growth is fast, and a darker latewood band formed later in the season. Together they show one year of wood production."),
    # Leaves and seasons
    ("Why do leaves change color in autumn?", "In autumn, shorter days and cooler weather slow chlorophyll production, so the green pigment fades. Yellow and orange pigments called carotenoids are then revealed, while red foliage comes from anthocyanins that the leaf newly produces as it prepares to drop."),
    ("Why do deciduous trees lose their leaves?", "Deciduous trees drop their leaves in autumn to save water and energy for winter. Losing broad leaves reduces water loss, since dry or frozen soil makes it hard for the roots to supply water."),
    ("What is the difference between deciduous and evergreen trees?", "Deciduous trees lose all their leaves each year, while evergreens keep foliage year-round. Evergreen needles and waxy leaves resist drought and cold, letting them photosynthesize in every season."),
    ("Why do evergreen trees keep their needles?", "Needles are adapted to save water, with a waxy coating and small surface area that reduces moisture loss. This lets evergreens keep their leaves through winter and resume growth quickly in spring."),
    ("Why are leaves usually green?", "Leaves look green because chlorophyll, the pigment used in photosynthesis, absorbs red and blue light and reflects green light. That reflected green light is what our eyes detect."),
    ("What is a leaf's role in a tree?", "A leaf is the tree's food factory. It captures sunlight with chlorophyll, takes in carbon dioxide through stomata, and produces glucose through photosynthesis while releasing oxygen."),
    ("What are veins on a leaf?", "Leaf veins carry water to the leaf tissue and transport the sugar it makes back to the rest of the tree. The pattern of veins is often characteristic of the tree species."),
    ("Why do leaves have stomata?", "Stomata are tiny pores on leaves that let the tree exchange gases. They open to take in carbon dioxide for photosynthesis and release oxygen and water vapor, but closing them limits water loss."),
    ("What is chlorophyll?", "Chlorophyll is the green pigment in leaves that captures light energy for photosynthesis. Its structure is similar to hemoglobin but with magnesium at the center instead of iron."),
    ("When do trees flower each year?", "Most trees flower in spring, when increasing daylight and warmth trigger bud break. Some trees flower later in summer or fall, and flowering time varies by species and climate."),
    # Reproduction and seeds
    ("How do trees reproduce?", "Trees reproduce by producing seeds, usually inside flowers or cones. Pollen moves between flowers by wind, insects, or animals, and after fertilization, seeds develop and are dispersed to grow into new trees."),
    ("What is a seed?", "A seed is a baby tree in a protective package. It contains an embryo, a food supply called endosperm, and a protective seed coat, and it stays dormant until conditions are right to germinate."),
    ("How do seeds spread?", "Seeds spread by wind, water, animals, and gravity. Wind carries light winged seeds like maple samaras, animals eat fruit and drop the seeds, and burrs stick to fur or clothing."),
    ("What is a maple samara?", "A samara is a winged seed that spins as it falls from the tree. Maple samaras can travel far on the wind, helping the tree spread its offspring beyond the parent's shade."),
    ("What is germination?", "Germination is when a seed begins to grow into a new plant. It needs water, oxygen, and the right temperature to swell, break its seed coat, and send out a root and a shoot."),
    ("Why do trees make so many seeds?", "Trees make thousands of seeds because very few survive. Most seeds are eaten, damaged, or land in poor conditions, so producing many increases the chance that at least one will grow into a new tree."),
    ("What is an acorn?", "An acorn is the nut and seed of oak trees. It contains a single seed protected by a tough shell and a cup-like cap, and it provides a rich food source for squirrels, birds, and deer."),
    ("What is a cone?", "A cone is the seed-bearing structure of conifer trees like pines and firs. Male cones shed pollen while female cones hold seeds between their woody scales, which open to release them when ripe."),
    ("What is a mast year?", "A mast year is when trees such as oaks and beeches produce an unusually large crop of nuts or seeds all at once. The boom overwhelms seed-eaters so many acorns survive to germinate."),
    ("Can a tree grow from a branch?", "Yes, many trees can grow from a branch through a cutting. A branch cut and rooted in soil can develop its own roots and grow into a new tree, a method commonly used to clone fruit trees."),
    # Famous trees and species
    ("What is the tallest tree species?", "The tallest tree species is the coast redwood of California. The current record holder is a coast redwood called Hyperion, standing about 380 feet (115 meters) tall."),
    ("What is the largest tree in the world?", "The largest tree by volume is General Sherman, a giant sequoia in California. It stands about 275 feet tall with a trunk volume of over 52,000 cubic feet."),
    ("What is the oldest known tree?", "The oldest known single tree is a Great Basin bristlecone pine in California called Methuselah, estimated at over 4,800 years old. Clonal trees can be far older."),
    ("What is an oak tree?", "An oak is a large hardwood tree that produces acorns. There are about 600 species of oaks, valued for strong timber, shade, and the wildlife that relies on their acorns and leaves."),
    ("What is a maple tree?", "A maple is a hardwood tree known for its lobed leaves, winged samaras, and brilliant autumn color. Some maples produce sweet sap that is boiled into maple syrup."),
    ("What is a pine tree?", "A pine is a conifer tree with long needles and woody cones. Pines are evergreen, keep their needles for several years, and are a major source of timber, resin, and pine nuts."),
    ("What is a birch tree?", "A birch is a fast-growing tree with smooth, peeling bark marked by horizontal lines. White bark birches are visually striking, and birch wood is used for furniture, paper, and veneers."),
    ("What is a willow tree?", "A willow is a moisture-loving tree with long, slender leaves and flexible branches. Weeping willows are known for their drooping form, and willows root easily from cuttings placed in wet ground."),
    ("What is a baobab tree?", "The baobab is an African tree with a massive, bottle-shaped trunk that stores water. It can live over 2,000 years, and its fruit pulp and leaves are used as food and medicine."),
    ("What is a sequoia?", "A sequoia is one of the giant redwood trees of California. Giant sequoias have the largest trunk volume of any tree, while coast redwoods are the tallest."),
    ("What is a baobab's nickname?", "The baobab is often called the upside-down tree because its bare branches look like roots reaching toward the sky. Its thick trunk stores water for dry seasons."),
    ("What is a bonsai tree?", "A bonsai is a miniature tree grown in a shallow pot and pruned to stay small. Bonsai is an art form, not a species; any tree can be bonsai with continual pruning and training."),
    ("What is a eucalyptus?", "Eucalyptus is a fast-growing evergreen tree native to Australia. Its leaves contain fragrant oils used in medicine and cleaning, and koalas feed almost entirely on certain eucalyptus leaves."),
    ("What is a mangrove?", "A mangrove is a tree that grows in saltwater coastal mudflats in tropical regions. Their tangled roots trap sediment, protect shorelines from erosion, and provide nursery habitat for fish."),
    ("What is a palm tree?", "A palm is a tropical plant with an unbranched trunk and a crown of large, fan-like or feather-like leaves. Palms are not true hardwood trees; they belong to a flowering plant family of their own."),
    # Humans and trees
    ("How do trees help clean the air?", "Trees clean the air by absorbing carbon dioxide and releasing oxygen during photosynthesis. They also trap dust and pollutants on their leaves, improving air quality in cities."),
    ("Why are forests called carbon sinks?", "Forests are carbon sinks because they absorb more carbon dioxide than they release. The carbon is stored in trunks, branches, roots, and soil, helping slow climate change."),
    ("How much carbon does a tree store?", "The amount varies by species, size, and age, but a mature tree can store about 20 to 50 kg of carbon dioxide per year. Over a lifetime a large tree can hold a tonne or more."),
    ("How do forests make rain?", "Forests influence rainfall by releasing water vapor from leaves into the air through transpiration. In large rainforests this moisture rises, condenses into clouds, and falls back as rain."),
    ("What is transpiration?", "Transpiration is the loss of water vapor from a tree's leaves through stomata. It pulls water up from the roots, cools the leaves, and moves nutrients through the tree."),
    ("What is deforestation?", "Deforestation is the clearing of forests for farming, timber, or development. It releases stored carbon, destroys habitat, erodes soil, and reduces rainfall over time."),
    ("Why do cities plant trees?", "Cities plant trees for shade, cooling, and air quality. Trees lower temperatures through evaporation and shade, absorb carbon and pollutants, reduce stormwater runoff, and improve mental well-being."),
    ("What is a windbreak?", "A windbreak is a row of trees planted to block or slow wind. It protects crops from drying and wind damage, keeps soil from eroding, and can reduce heating costs near buildings."),
    ("What is arboriculture?", "Arboriculture is the care and management of individual trees and woody plants, such as pruning, planting, and treating disease. It focuses on tree health, safety, and aesthetic value."),
    ("What is an arborist?", "An arborist is a trained professional who cares for trees, including pruning, planting, diagnosing diseases, and removing hazardous branches. They work to keep trees healthy and safe."),
    ("Why do trees live so long?", "Trees live long because they keep adding new tissue each year instead of replacing old cells. Their durable wood, ability to heal wounds, and dormant season allow them to survive decades or centuries."),
    ("What is tree sap used for?", "Tree sap is used to make many products. Maple sap becomes syrup, pine sap yields resin and turpentine, and rubber trees produce latex from their sap."),
    ("What should you do if you find a fallen baby tree?", "You can gently plant a young seedling if it has roots and the spot gets appropriate light and water. Planting trees helps forests recover and captures carbon from the air."),
    ("Why do people plant trees on Arbor Day?", "Arbor Day is a holiday dedicated to planting and caring for trees. It was first celebrated in Nebraska in 1872, inspiring people worldwide to plant trees for shade, beauty, and the environment."),
    ("What is the world's most common tree species?", "By some counts, the most abundant tree species is an oak called Quercus obtusata in central Mexico, though estimates differ. Overall, willow, aspen, and birch species grow over huge ranges."),
    ("What tree makes the best shade?", "Broad, spreading trees like maples, oaks, and sycamores make excellent shade. Dense canopies with large leaves block sunlight and cool the ground below."),
    # Wildlife and ecosystem
    ("What animals use trees?", "Countless animals use trees for food, shelter, and nesting. Birds build nests in branches, squirrels eat nuts and seeds, insects bore into bark, and many animals den in hollow trunks."),
    ("Why do birds nest in trees?", "Trees give birds a safe, high place to build nests, hidden from many predators. Sturdy branches support the nest, and leaves provide cover from the weather and observation."),
    ("What is a tree hollow?", "A tree hollow is a cavity in a trunk or branch, often formed as the heartwood rots. It becomes vital habitat for owls, bats, squirrels, and other wildlife that shelter or nest inside."),
    ("What is a keystone tree species?", "A keystone species is a tree that a whole community depends on. For example, oaks support more insect and bird species than almost any other tree, so their loss ripples through the ecosystem."),
    ("How do fungi help trees?", "Many fungi form a partnership with tree roots called mycorrhiza, where the fungus extends the tree's ability to absorb water and nutrients. In exchange the tree gives the fungus sugars."),
    ("What is a mycorrhizal network?", "A mycorrhizal network is a web of underground fungi connecting tree roots. It lets trees share water, nutrients, and even warning signals when pests attack."),
    ("Why do trees keep some leaves in winter?", "Evergreen trees keep their leaves or needles to be ready to photosynthesize as soon as conditions allow. Their tough, waxy leaves can survive frost without freezing damage."),
    ("What happens when trees are too crowded?", "When trees are crowded they compete for sunlight, water, and nutrients. They grow tall but thin, weaker branches die off, and the forest naturally thins as weaker trees fail."),
    ("What is a forest floor?", "The forest floor is the ground layer of leaves, twigs, and fallen wood under trees. Decomposers break it down into rich soil, recycling nutrients back to the living trees."),
    ("Who breaks down dead trees?", "Decomposers like fungi, bacteria, and insects break down dead trees. Their work returns nutrients to the soil and creates habitat while clearing the forest of limbs."),
    ("What is the relationship between trees and mycelium?", "Trees and mycelium form a mutual partnership. Mycelium, the network of fungi, helps trees absorb water and minerals, while trees feed the fungi with carbohydrates from photosynthesis."),
    ("Do trees communicate?", "Trees communicate partly through chemical signals and fungal networks. When attacked by insects, they release chemicals warning neighbors, which can then boost their own defenses."),
    ("What are phloem and xylem?", "Xylem and phloem are the transport tissues of a tree. Xylem carries water and minerals up from the roots, while phloem carries the sugars made in the leaves to the rest of the tree."),
    ("How is tree sugar transported?", "Sugars are transported from the leaves through the phloem in a water-based solution. The movement is driven by pressure from the sugars themselves, flowing to roots, fruits, and other parts."),
    ("What is the water cycle role of trees?", "Trees pump water from the soil into the air through transpiration, feeding the water cycle. Their roots slow runoff and filter water, and their shade reduces evaporation from the ground."),
    ("How much water does a tree drink in a day?", "A large tree can absorb hundreds of liters of water per day, most of which is released as vapor through its leaves. The amount depends on size, species, temperature, and available moisture."),
    ("What is a deciduous forest?", "A deciduous forest is a woodland of broad-leaved trees that lose their leaves each autumn, common in temperate regions with distinct seasons."),
    ("What is a coniferous forest?", "A coniferous forest is a woodland dominated by cone-bearing evergreens like pines, spruces, and firs. These forests often grow in cooler climates or poor soils."),
    ("What is a rainforest?", "A rainforest is a dense, wet forest receiving heavy rainfall, usually in tropical regions. It holds the greatest diversity of tree species and wildlife on Earth."),
    ("What is a savanna tree?", "Savanna trees are scattered trees growing in grasslands with seasonal rainfall. Species like the acacia survive long dry seasons with deep roots, water-storing trunks, or tough leaves."),
    ("What are the oldest clonal trees?", "Clonal trees reproduce by sending up new trunks from one giant root system, so they can survive for millennia. The oldest known clone is a Norway spruce in Sweden over 9,500 years old."),
    ("What is a tree line?", "The tree line is the altitude or latitude where trees stop growing. Beyond it, cold, wind, or drought prevent trees from surviving, and only shrubs, grasses, or rock remain."),
    # Wood and products
    ("What is wood made of?", "Wood is made mostly of cellulose fibers held together by lignin, both built from carbon the tree captured from the air. That structure gives wood its strength and stiffness."),
    ("What is oak wood used for?", "Oak is a strong, attractive hardwood used for furniture, flooring, barrels, and shipbuilding. Its tight grain and resistance to wear have made it a favorite for centuries."),
    ("What is cedar wood used for?", "Cedar is a softwood known for its pleasant scent, light weight, and natural resistance to rot and insects. It is often used for outdoor lumber, decking, closets, and chests."),
    ("What is plywood?", "Plywood is a building panel made by gluing thin layers, or plies, of wood together with the grain of each layer at right angles to the next. This cross-lamination gives it strength in all directions."),
    ("What is paper made from?", "Paper is made from wood pulp. The tree is chipped, cooked with chemicals to separate the cellulose fibers, then pressed and dried into thin sheets."),
    ("What is resin?", "Resin is a sticky fluid produced by trees, especially pines, that hardens to protect wounds and repel insects. It is distilled into turpentine, varnishes, and adhesives."),
    ("What is a timber?", "Timber is wood prepared for construction and carpentry. Trees are logged, sawed into beams and boards, and dried before being used to frame buildings and make wood products."),
    ("What is charcoal made from?", "Charcoal is made by heating wood in a low-oxygen environment so it burns off water and volatile gases, leaving nearly pure carbon. It burns hot and clean and is used for cooking and art."),
    ("What is hardwood?", "Hardwood comes from flowering trees like oaks and maples, which generally have dense, complex wood. It is used for furniture, flooring, and tools because of its strength."),
    ("What is softwood?", "Softwood comes from conifer trees like pines and firs. Despite the name, some softwoods are heavy, but they are usually easier to saw and are used widely for construction timber."),
    ("Why is walnut wood special?", "Walnut is a rich, dark brown hardwood prized for fine furniture and gunstocks. Its warm color, beautiful grain, and stability have made it a luxury wood for centuries."),
    ("What is an ash tree used for?", "Ash is a strong, springy hardwood used for tool handles, baseball bats, and furniture. Its shock resistance comes from long, straight fibers that flex without breaking."),
    ("What is mahogany?", "Mahogany is a tropical hardwood prized for its deep red-brown color, straight grain, and stability. It has long been used for fine furniture, boats, and guitars."),
    ("What is teak?", "Teak is a dense tropical hardwood extremely resistant to weather, rot, and insects. Its natural oils make it ideal for outdoor furniture and boat decks."),
    ("What is rosewood?", "Rosewood is a dense, richly colored tropical hardwood with fragrant oils, named for its scent. It is used for fine furniture and musical instruments like guitars and pianos."),
    ("What is birchbark used for?", "Birchbark is waterproof and peels into sheets that have been used for canoes, containers, and writing material. Native peoples of the north made durable canoes from it."),
    ("What is cork?", "Cork is the outer bark of the cork oak, harvested without harming the tree. Its air-trapping cells make it light, elastic, and water-resistant, perfect for bottle stoppers and flooring."),
    ("What is rubber made from?", "Natural rubber comes from the latex sap of the rubber tree. Farmers make diagonal cuts in the bark, collect the milky latex, and process it into elastic rubber products."),
    ("What is a fruit tree?", "A fruit tree is a cultivated tree that produces edible fruit, such as apples, oranges, and cherries. Fruit trees are often grafted onto hardy rootstocks to control size and improve growth."),
    ("How are fruit trees grafted?", "Grafting joins a fruiting branch, the scion, onto the roots of another tree, the rootstock. The two fuse together, combining the desired fruit variety with the rootstock's size and hardiness."),
    ("What is an orchard?", "An orchard is a planted area where fruit or nut trees are grown for harvest. Orchards are arranged so trees get full sunlight, good airflow, and easy access for picking."),
    ("What is the difference between a fruit and a seed?", "A fruit is the mature, often fleshy structure holding seeds, while the seed is the baby plant inside. Other parts of the fruit may be edible, large, or protective."),
    ("What is an avocado tree's fruit?", "The avocado is a tree that bears a creamy, single-seeded berry. Its fruit is rich in healthy fats and grows best in warm, frost-free climates."),
    ("What is an olive tree?", "The olive is a slow-growing Mediterranean tree with silvery leaves that lives for centuries. Its fruit is pressed for olive oil and cured for eating."),
    ("What is a fig tree?", "The fig is a tree with tangled branches whose flowers bloom inside a fleshy structure called a syconium, which ripens into the fruit we eat. Figs are pollinated by tiny wasps in a close partnership."),
    ("What is an apple tree?", "The apple is a temperate fruit tree of the rose family. Thousands of apple varieties exist, most needing another variety nearby for cross-pollination."),
    ("What is a cherry tree?", "The cherry is a flowering fruit tree valued for both its blossoms and fruit. Cherry wood is prized for furniture, and cherry trees often flower spectacularly in spring."),
    ("What is a lemon tree?", "The lemon is a small evergreen citrus tree with fragrant flowers. Its sour fruit is rich in vitamin C and is used widely in cooking, drinks, and cleaning."),
    ("What is an orange tree?", "The orange is an evergreen citrus tree grown in warm regions. Its fruit is a sweet orange berry rich in vitamin C, and both its flowers and fruit release fragrant oils."),
    ("What is a pecan tree?", "The pecan is a large North American hickory tree prized for its sweet, oily nuts. Pecan orchards bear nuts for decades and are a major crop in the southern U.S."),
    ("What is a walnut tree?", "The walnut is a large tree grown for its nuts and fine dark wood. Walnut trees produce compounds that can inhibit other plants growing nearby."),
    ("What is a coconut palm?", "The coconut palm is a tropical palm that produces large coconuts in a woody husk. Every part of the coconut is used, from water and flesh to oil, coir, and shell."),
    ("What is a banana plant?", "The banana is a giant herb, not a true tree, despite looking like one. Its trunk is made of layered leaf bases, and each stem produces one bunch of fruit before dying back."),
    ("What is a mango tree?", "The mango is a tropical evergreen fruit tree native to South Asia. Its sweet, juicy fruit is one of the most popular in the world, and the tree can grow over 30 meters tall."),
    ("What is a pomegranate tree?", "The pomegranate is a shrub or small tree with bright red fruit packed with jewel-like seeds. It grows in warm, dry climates and has been cultivated for thousands of years."),
    ("What is a peach tree?", "The peach is a small deciduous fruit tree with fragrant pink blossoms. Its fuzzy fruit has a single hard stone, and peaches grow best in regions with cold winters and warm summers."),
    ("What is a palm fruit?", "Many palms bear fruit, the most famous being coconuts and dates. Date palms grow sweet dates in heavy clusters, and their fronds provide shade and building material in deserts."),
    ("What is a date palm used for?", "The date palm provides sweet dates, shade, and building material in desert oases. Its leaves become mats and roofing, and its trunk is used for timber."),
    ("What is a cashew tree?", "The cashew is a tropical tree whose kidney-shaped seed grows outside the fleshy cashew apple. The seed is the edible cashew nut, and the apple is used for juice."),
    ("What is an almond tree?", "The almond is a small tree that produces stone fruits whose pits are the almonds we eat. It flowers early in spring and is grown in warm, dry climates."),
    ("What is a mulberry tree?", "The mulberry is a fast-growing tree bearing clusters of sweet berries. Its leaves are the food of silkworms, and its fruit stains and feeds wildlife."),
]

lines = []
for q, a in pairs:
    lines.append(f"User: {q}")
    lines.append(f"Joe: {a}")
    lines.append("")

_REPO = os.path.dirname(os.path.abspath(__file__))
with open(os.path.join(_REPO, "data", "experts", "tree", "tree_train.txt"), "w") as f:
    f.write("\n".join(lines))

# Remove the malformed pair (duplicate "What is a eucalyptus?" listed as tuple with missing comma artifact)
print(f"Wrote {len([p for p in pairs if isinstance(p, tuple)])} pairs ({len(lines)} lines)")