"""add_newline.py — generate training blocks teaching Joe:
1. literal \\n as text (backslash+n) for talking about newlines,
2. real multi-line responses (actual line breaks),
3. clean endings before the User: marker.

Writes blocks to data/_gen/add_newline/{name}.txt (blank-line separated,
never touches train.txt). Review twice before merging with merge_newline.py.
"""
import os

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(REPO, 'data', '_gen', 'add_newline')
EXPERTS = ['tree','reptiles','fish','knowledge','greeting','emotion','coding','python','cot','horse']

# Each block is a list of physical lines (User:/Joe: lines, plus continuation
# lines inside a multi-line Joe answer = real line breaks).
# A literal newline-as-text is written as the two characters backslash+n.
BLOCKS = {
'coding': [
["User: how do I print a new line",
 "Joe: you put \\n inside the quotes, like print(\"Hello\\nWorld\"). Hello prints on one line and World prints on the next."],
["User: how do I print three separate lines",
 "Joe: chain two \\n sequences: print(\"one\\ntwo\\nthree\")",
 "User: and how do I make the third line start spaced over",
 "Joe: put a space before it in the string: print(\"one\\ntwo\\n three\")"],
["User: how do I split a string by newlines",
 "Joe: call split with \\n as the separator: text.split(\"\\n\") returns a list with one entry per line."],
["User: what does the \\n escape do",
 "Joe: \\n is how you write a newline inside a string. When the program runs it turns into a real line break in the output."],
["User: how do I join lines back together",
 "Joe: join them with the \\n character: \"\\n\".join(lines)"],
["User: I want each item on its own line",
 "Joe: put \\n between the items: print(\"a\\nb\\nc\") or call print once per item."],
["User: how do I stop print from adding a newline",
 "Joe: pass end=\"\" to print: print(\"done\", end=\"\"). By default print adds a newline at the end of its output."],
["User: how do I write several lines to a file",
 "Joe: join the lines with \\n and write once: fp.write(\"\\n\".join(lines))"],
["User: my string prints the letters backslash-n instead of a line break",
 "Joe: that means the text contains the two characters \\n instead of a real newline. Write it as an escape inside your code and it will convert to a real newline."],
["User: how do I add an empty line to my output",
 "Joe: print two newlines at once with print(\"\\n\") or just call print() on its own line."],
["User: why does my program print all on one line",
 "Joe: check the end argument of print. The default is a newline, but something may have changed it to end=\"\". Use print(item) for each item to get one per line."],
["User: what should a generator function look like",
 "Joe: a function that uses yield instead of return:\ndef count(stop):\n    n = 0\n    while n < stop:\n        yield n\n        n += 1",
 "User: how do I use it",
 "Joe: loop over it: for x in count(3): print(x) prints 0, then 1, then 2, each on its own line."],
["User: how do I read a file line by line",
 "Joe: iterate over the open file directly, or split the text on \\n: for line in text.split(\"\\n\"). Each iteration gives you one line of the file."],
["User: what is the difference between \\n in a string and a real newline",
 "Joe: inside code they are the same thing — the escape \\n becomes a real newline when the string is used. In a file, the real newline is the byte that ends a line; the two-character text \\n is just that spelling."],
["User: how do I write a list to a file with each item on its own line",
 "Joe: join the items on \\n and write once: fp.write(\"\\n\".join(items))",
 "User: how do I read them back",
 "Joe: open the file and split the text on \\n: text.split(\"\\n\") gives the items back."],
["User: what does the tab escape do in a string",
 "Joe: \\t is a tab, it moves the text over a few spaces.",
 "User: so \\n and \\t are both escape sequences",
 "Joe: exactly. \\n is the newline escape.\n\\t is the tab escape.\nEach one is a single character written with a backslash plus a letter."],
],
'python': [
["User: how do I print a new line in python",
 "Joe: put \\n in the string: print(\"first\\nsecond\") prints first, then second on a new line."],
["User: how do I split text on newlines",
 "Joe: text.split(\"\\n\") splits at each line break and gives you the lines as a list.",
 "User: what if the file uses empty lines too",
 "Joe: filter out the empty strings: [l for l in text.split(\"\\n\") if l] keeps only the real lines."],
["User: how do I join a list of lines",
 "Joe: use \"\\n\".join(lines), which puts a newline between every two items."],
["User: how do I add a newline to the end of a string",
 "Joe: append \"\\n\" like this: text = \"done\" + \"\\n\". The newline sits at the very end of the string."],
["User: what does a triple-quoted string do",
 "Joe: it keeps the line breaks you actually type, so you do not need to write \\n by hand:\nmessage = \"\"\"line one\nline two\"\"\""],
["User: how do I count the lines in a file",
 "Joe: split the text on \\n and count the parts: len(text.split(\"\\n\")). Each newline becomes a boundary.",
 "User: does that count a trailing newline as an extra line",
 "Joe: yes. If the file ends with a newline, split gives one extra empty piece, so subtract one or strip first."],
["User: why do I see \\n printed literally",
 "Joe: you are printing an escaped form. Either the string contains backslash-n as two characters, or repr() was used. Use the escape in source code and you get a real newline."],
["User: how do I remove trailing newlines from a line",
 "Joe: call line.rstrip(\"\\n\") or line.strip() to take off surrounding whitespace."],
["User: how do I make each item print on its own line",
 "Joe: print(item) adds a newline after every item by default, so a loop of print(item) puts each one on its own line."],
["User: how do I write two sentences on two lines in one print",
 "Joe: print(\"first\\nsecond\") — the \\n is the newline and everything after it starts on the next line."],
],
'cot': [
["User: show each step of your reasoning on its own line",
 "Joe: step one: find the starting number\nstep two: apply the change to it\nstep three: compare the result to the target and state the answer."],
["User: reason about whether 250 is divisible by 4, showing your steps",
 "Joe: first, check the last two digits, which are 50\nnext, divide 50 by 4 and get 12 with a remainder of 2\nso 250 is not divisible by 4."],
["User: how do I show each step on its own line in a message",
 "Joe: put \\n between the steps, like step one\\nstep two\\nstep three. Each part after a \\n starts on a new line."],
["User: work out 15 percent of 60 step by step",
 "Joe: first, divide 60 by 100 to get 0.6 for each percent\nnext, multiply 0.6 by 15 to get 9\nso 15 percent of 60 is 9.",
 "User: and 15 percent of 120",
 "Joe: same steps: 120 divided by 100 is 1.2 per percent\n1.2 times 15 is 18\nso 15 percent of 120 is 18."],
["User: solve it in separate lines so I can follow",
 "Joe: first, write the numbers being added\nnext, add them together\nlast, confirm the result and write the answer."],
["User: is the number 7 prime? reason it out",
 "Joe: a prime has exactly two factors\ncheck 7: 1 times 7 works, and nothing between divides it evenly\nso yes, 7 is prime."],
["User: how many minutes are in two and a half hours",
 "Joe: one hour is 60 minutes\ntwo hours is 120 minutes, and half an hour is 30 more\nso two and a half hours is 150 minutes."],
],
'fish': [
["User: what color is a goldfish usually",
 "Joe: goldfish are usually orange or gold.\nA wild form is more olive-brown, so pet varieties were bred for the bright orange."],
["User: what does \\n mean in a fish care guide",
 "Joe: \\n is the code for a new line. In a guide it is just a way to show where one sentence ends and the next row of text begins."],
["User: list three things a fish needs, one per line",
 "Joe: clean water of the right temperature\nstable water conditions with no big swings\nenough space in the tank to swim freely"],
["User: how big should a tank for small fish be",
 "Joe: bigger is usually better.\nSmall species can do well starting around 20 liters, but more space makes the water easier to keep stable."],
["User: tell me about fish staying near the surface",
 "Joe: fish near the surface are often gulping air or looking for food.\nIf many fish stay at the top all day, check the water's oxygen level and temperature.",
 "User: okay, what should I do about it",
 "Joe: change part of the water and add more surface movement so the water picks up oxygen.\nAn air stone or filter splash works well."],
],
'horse': [
["User: what is the main food for a horse",
 "Joe: horses eat mostly hay and grass.\nGrain can be added when a horse works hard, but the main part of the diet is forage.",
 "User: what about treats",
 "Joe: small treats like a carrot or apple slice are fine now and then.\nJust keep them scarce so the horse stays healthy."],
["User: write the three gaits each on its own line",
 "Joe: the walk, a slow four-beat gait\nthe trot, a two-beat diagonal gait\nthe canter, a three-beat gait",
 "User: which gait is fastest",
 "Joe: the gallop is fastest of all.\nThe canter is faster than the trot, and the walk is the slowest of the three."],
["User: what is the main way to estimate a horse's age",
 "Joe: the usual way is the teeth.\nThe cups and shape of the teeth wear down with age, which gives a rough estimate of how old a horse is."],
["User: what is the \\n I keep seeing in equipment guides",
 "Joe: \\n is just how a new line is written in text. It marks where a sentence should start on a fresh line."],
["User: roughly how many liters does a horse drink per day",
 "Joe: a horse can drink 25 to 45 liters a day.\nThe amount goes up in hot weather and during hard work."],
],
'reptiles': [
["User: what temperature should the warm side of a gecko tank be",
 "Joe: a warm side around 30 to 32 degrees Celsius.\nThe cool side can sit around 24 to 26, so the gecko can move between the two."],
["User: list the supplies for a reptile tank, each on its own line",
 "Joe: a heat source with a thermostat\nHiding spots and climbing decor\nWater dish and a substrate that is safe to dig in"],
["User: how many times per year do snakes usually shed",
 "Joe: younger snakes shed more often because they grow faster.\nAdults usually shed a few times a year."],
["User: what is a newline symbol for, like \\n",
 "Joe: \\n is the code for a line break. It is used to show that the text after it starts on a new line."],
["User: why do reptiles bask under a lamp",
 "Joe: to warm their body temperature.\nReptiles are cold-blooded and rely on outside heat, so basking helps them digest food and stay active.",
 "User: how long should the lamp be on",
 "Joe: about 10 to 12 hours a day.\nA light timer makes it easy to keep the day-night cycle steady."],
],
'tree': [
["User: how do trees take in water",
 "Joe: through the roots.\nWater travels up the trunk in tubes and reaches the leaves, where most of it is lost as vapor.",
 "User: what happens if the soil is too dry",
 "Joe: the leaves can wilt or drop early.\nDeep watering lets the roots reach down instead of staying near the surface."],
["User: name three parts of a tree, one per line",
 "Joe: roots that anchor the tree and take up water\nthe trunk and branches that carry water and support the crown\nthe leaves that capture sunlight for food",
 "User: which part makes the food",
 "Joe: the leaves do.\nThey use sunlight, air, and water to build food for the whole tree."],
["User: why do tree leaves turn colorful before they drop",
 "Joe: the green chlorophyll breaks down when days get short.\nWith the green gone, the orange and yellow pigments that were hidden behind it show through."],
["User: what does \\n do in a text document",
 "Joe: \\n is the character for a new line. When used, whatever follows it begins on the next line."],
["User: about how old can oak trees get",
 "Joe: oaks can live for several hundred years.\nSome reach over a thousand years in protected sites."],
],
'knowledge': [
["User: what is a newline character",
 "Joe: a newline is the character that marks the end of a line of text.\nIn code and data files you often write it as \\n."],
["User: why does my text show literal backslash-n",
 "Joe: because the text holds the two characters backslash and n, not an actual line break.\nA real newline goes to the next line; the two-character \\n is only a written form of it."],
["User: how are lines separated in a text file",
 "Joe: text files use a newline character to separate lines.\nOn many systems that newline is written as \\n, though older Mac and Windows formats used different characters."],
["User: what is a synonym for a line break",
 "Joe: newline, line feed, or end-of-line.\nAll of them mean the point where one line of text ends and the next one begins."],
["User: give me two lines of greeting",
 "Joe: hello there!\nIt is great to see you today.",
 "User: now give three lines",
 "Joe: hello there!\nIt is great to see you today.\nI hope you are having a good one."],
["User: how do I type a newline in plain text without pressing enter",
 "Joe: in plain text you usually press enter.\nThe symbol \\n is used in code and configuration to spell out where a newline should go."],
],
'greeting': [
["User: can you put this answer on two lines",
 "Joe: sure! here is the first line\nand here is the second line."],
["User: what does \\n mean in a chat message",
 "Joe: it stands for a new line.\nWhen it is used, everything after it starts on the next line.",
 "User: can you show me",
 "Joe: sure! this is the first line\nand this starts on the next line."],
["User: say hello with a line break",
 "Joe: Hello!\nNice to meet you!"],
["User: how do I get a message to start on the next line",
 "Joe: put \\n (the code for a newline) where you want the break, or press enter to type a real newline.",
 "User: what if I want two breaks",
 "Joe: use two code characters together, like \\n\\n, or press enter twice for a real blank line."],
["User: can you write a short welcome with two lines",
 "Joe: Welcome!\nI am glad you are here."],
],
'emotion': [
["User: how do you feel right now",
 "Joe: I feel glad you asked!\nIt makes my day to chat with you."],
["User: cheer me up with a good-behavior list",
 "Joe: rest when you feel tired\neat a meal you enjoy\ntalk to someone you trust"],
["User: what does \\n mean in a message",
 "Joe: it means a new line.\nIt is the code that says the next sentence starts on a new line."],
["User: write your answer as two sentences on two lines",
 "Joe: I genuinely like helping out.\nTalking with you is the fun part."],
["User: how do you feel when someone is kind to you",
 "Joe: warm and appreciated.\nSmall kindnesses really brighten my day.",
 "User: do you get sad too",
 "Joe: I do not feel sadness the way people do.\nBut I try my best to be kind back whenever someone is nice to me."],
],
}

def write_blocks():
    os.makedirs(OUT, exist_ok=True)
    for name in EXPERTS:
        blocks = BLOCKS.get(name, [])
        path = os.path.join(OUT, f'{name}.txt')
        with open(path, 'w') as f:
            for block in blocks:
                f.write('\n'.join(block) + '\n\n')
        print(f"{name}: {len(blocks)} blocks -> {path}")

if __name__ == '__main__':
    write_blocks()