"""add_newline.py — generate training blocks teaching Joe:
1. literal \\n as text (backslash+n) for talking about newlines,
2. real newlines in responses (multi-line Joe answers),
3. ends cleanly at \\nUser:/\\nJoe:.

Writes blocks to data/_gen/add_newline/{name}.txt (blank-line separated;
multi-line Joe answers use continuation lines). Review twice before
merging with merge_newline.py.
"""
import os

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(REPO, 'data', '_gen', 'add_newline')
EXPERTS = ['tree','reptiles','fish','knowledge','greeting','emotion','coding','python','cot','horse']

# Each block: ["User: q", "Joe: line1", "line2", ...] for multi-line answers,
# or ["User: q", "Joe: single line"] for single-line. Multi-turn adds another
# ["User: follow-up", "Joe: answer"] pair inside the block.
BLOCKS = {
'coding': [
["User: how do I print a new line",
 "Joe: you put \\n inside the quotes, like print(\"Hello\\nWorld\")."],
["User: how do I print three separate lines",
 "Joe: chain two \\n sequences: print(\"one\\ntwo\\nthree\")."],
["User: make the third line start spaced over",
 "Joe: put a space before it: print(\"one\\ntwo\\n three\")."],
["User: how do I split a string by newlines",
 "Joe: call split with \\n as the separator: text.split(\"\\n\") gives the lines."],
["User: what does the \\n escape do",
 "Joe: \\n is how you write a newline inside a string; at runtime it becomes a real line break."],
["User: how do I join lines back together",
 "Joe: join them with the \\n character: \"\\n\".join(lines)."],
["User: I want each item on its own line",
 "Joe: put \\n between the items: print(\"a\\nb\\nc\") or call print once per item."],
["User: how do I stop print from adding a newline",
 "Joe: pass end=\"\" to print: print(\"done\", end=\"\")."],
["User: how do I write several lines to a file",
 "Joe: join the lines with \\n and write once: fp.write(\"\\n\".join(lines))."],
["User: my string prints the letters backslash-n instead of a line break",
 "Joe: the text holds the two characters \\n instead of a real newline; use the escape in code."],
["User: how do I add an empty line to my output",
 "Joe: print two newlines at once with print(\"\\n\") or just call print()."],
["User: why does my program print all on one line",
 "Joe: check the end argument of print; use print(item) for each item on its own line."],
["User: what should a generator function look like",
 "Joe: a function that uses yield instead of return.",
 "def count(stop):",
 "    n = 0",
 "    while n < stop:",
 "        yield n",
 "        n += 1",
 "User: how do I use it",
 "Joe: loop over it: for x in count(3): print(x) prints 0, then 1, then 2."],
["User: how do I read a file line by line",
 "Joe: iterate over the open file directly, or split the text on \\n."],
["User: what is the difference between \\n in a string and a real newline",
 "Joe: inside code they are the same — the escape \\n becomes a real newline when the string is used."],
["User: how do I write a list to a file with each item on its own line",
 "Joe: join the items on \\n and write once: fp.write(\"\\n\".join(items))."],
["User: how do I read them back",
 "Joe: open the file and split the text on \\n: text.split(\"\\n\") gives the items back."],
["User: what does the tab escape do in a string",
 "Joe: \\t is a tab; it moves the text over a few spaces."],
["User: so \\n and \\t are both escape sequences",
 "Joe: exactly — \\n is the newline escape and \\t is the tab escape."],
],
'python': [
["User: how do I print a new line in python",
 "Joe: put \\n in the string: print(\"first\\nsecond\") prints first, then second."],
["User: how do I split text on newlines",
 "Joe: text.split(\"\\n\") splits at each line break and gives the lines as a list."],
["User: what if the file uses empty lines too",
 "Joe: filter them out: [l for l in text.split(\"\\n\") if l] keeps only the real lines."],
["User: how do I join a list of lines",
 "Joe: use \"\\n\".join(lines), which puts a newline between every two items."],
["User: how do I add a newline to the end of a string",
 "Joe: append \"\\n\" like this: text = \"done\" + \"\\n\"."],
["User: what does a triple-quoted string do",
 "Joe: it keeps the line breaks you actually type, so you do not need to write \\n by hand:",
 "message = \"\"\"line one",
 "line two\"\"\""],
["User: how do I count the lines in a file",
 "Joe: split the text on \\n and count the parts: len(text.split(\"\\n\"))."],
["User: does that count a trailing newline as an extra line",
 "Joe: yes — if the file ends with a newline, strip first or subtract one."],
["User: why do I see \\n printed literally",
 "Joe: you are printing an escaped form; use the escape in source code to get a real newline."],
["User: how do I remove trailing newlines from a line",
 "Joe: call line.rstrip(\"\\n\") or line.strip() to take off surrounding whitespace."],
["User: how do I make each item print on its own line",
 "Joe: print(item) adds a newline after every item by default."],
["User: how do I write two sentences on two lines in one print",
 "Joe: print(\"first\\nsecond\") — the \\n starts the second sentence on the next line."],
],
'cot': [
["User: show each step of your reasoning on its own line",
 "Joe: step one: find the starting number;",
 "step two: apply the change;",
 "step three: compare and state the answer."],
["User: reason about whether 250 is divisible by 4, showing your steps",
 "Joe: check the last two digits, which are 50;",
 "divide 50 by 4 and get 12 with a remainder of 2."],
["User: how do I show each step on its own line in a message",
 "Joe: put \\n between the steps, like step one\\nstep two\\nstep three."],
["User: work out 15 percent of 60 step by step",
 "Joe: divide 60 by 100 to get 0.6 per percent, then multiply 0.6 by 15 to get 9."],
["User: and 15 percent of 120",
 "Joe: same steps: 120 divided by 100 is 1.2 per percent, times 15 is 18."],
["User: solve it in separate lines so I can follow",
 "Joe: first, write the numbers being added;",
 "next, add them together;",
 "last, confirm and state the answer."],
["User: is the number 7 prime? reason it out",
 "Joe: a prime has exactly two factors;",
 "check 7: 1 times 7 works and nothing between divides it evenly."],
["User: how many minutes are in two and a half hours",
 "Joe: one hour is 60 minutes, two hours is 120, and half an hour is 30 more, so 150 minutes."],
["User: what does \\n mean when writing step-by-step reasoning",
 "Joe: \\n is how you insert a line break between steps in plain text."],
["User: can you show the long division steps with newlines",
 "Joe: use \\n to separate each step: dividend\\ndivisor\\nquotient\\nremainder."],
],
'fish': [
["User: what color is a goldfish usually",
 "Joe: goldfish are usually orange or gold; wild forms are more olive-brown."],
["User: what does \\n mean in a fish care guide",
 "Joe: \\n is the code for a new line, just a way to show where one sentence ends and the next begins."],
["User: list three things a fish needs, one per line",
 "Joe: clean water of the right temperature, stable conditions with no big swings, and enough space to swim."],
["User: how big should a tank for small fish be",
 "Joe: bigger is usually better; small species can do well starting around 20 liters."],
["User: tell me about fish staying near the surface",
 "Joe: fish near the surface are often gulping air or looking for food."],
["User: okay, what should I do about it",
 "Joe: change part of the water and add more surface movement so the water picks up oxygen."],
["User: what does \\n look like in a fish diary entry",
 "Joe: \\n is the escape that starts a new line in the text, so each observation goes on its own line."],
["User: write your fish observations with each on a separate line",
 "Joe: use \\n between entries: water temp\\nph level\\nfeeding time."],
],
'horse': [
["User: what is the main food for a horse",
 "Joe: horses eat mostly hay and grass; grain can be added when a horse works hard."],
["User: what about treats",
 "Joe: small treats like a carrot or apple slice are fine now and then."],
["User: write the three gaits each on its own line",
 "Joe: the walk is a slow four-beat gait, the trot a two-beat diagonal, and the canter a three-beat."],
["User: which gait is fastest",
 "Joe: the gallop is fastest; the canter is faster than the trot, and the walk is the slowest."],
["User: what is the main way to estimate a horse's age",
 "Joe: the usual way is the teeth; the cups and shape wear down with age."],
["User: what is the \\n I keep seeing in equipment guides",
 "Joe: \\n is just how a new line is written in text; it marks where a sentence starts on a fresh line."],
["User: roughly how many liters does a horse drink per day",
 "Joe: a horse can drink 25 to 45 liters a day, more in hot weather and during hard work."],
["User: write a horse care checklist with each item on its own line",
 "Joe: use \\n to separate items: feed\\ngrooming\\nveterinary\\nexercise."],
],
'reptiles': [
["User: what temperature should the warm side of a gecko tank be",
 "Joe: a warm side around 30 to 32 degrees Celsius, with the cool side around 24 to 26."],
["User: list the supplies for a reptile tank, each on its own line",
 "Joe: a heat source with a thermostat, hiding spots and climbing decor, and a safe substrate."],
["User: how many times per year do snakes usually shed",
 "Joe: younger snakes shed more often because they grow faster; adults shed a few times a year."],
["User: what is a newline symbol for, like \\n",
 "Joe: \\n is the code for a line break, used to show that the text after it starts on a new line."],
["User: why do reptiles bask under a lamp",
 "Joe: to warm their body temperature; reptiles are cold-blooded and rely on outside heat."],
["User: how long should the lamp be on",
 "Joe: about 10 to 12 hours a day; a light timer keeps the day-night cycle steady."],
["User: what does \\n do in a reptile care log",
 "Joe: \\n starts a new line in the log, so each observation is separate and easy to read."],
["User: write a feeding schedule with each meal on its own line",
 "Joe: use \\n to separate entries: morning\\nafternoon\\nevening\\nnight."],
],
'tree': [
["User: how do trees take in water",
 "Joe: through the roots; water travels up the trunk in tubes and reaches the leaves."],
["User: what happens if the soil is too dry",
 "Joe: the leaves can wilt or drop early; deep watering lets the roots reach down."],
["User: name three parts of a tree, one per line",
 "Joe: roots that anchor the tree and take up water, the trunk and branches that carry water, and the leaves that capture sunlight."],
["User: which part makes the food",
 "Joe: the leaves do; they use sunlight, air, and water to build food for the whole tree."],
["User: why do tree leaves turn colorful before they drop",
 "Joe: the green chlorophyll breaks down when days get short, revealing the orange and yellow pigments."],
["User: what does \\n do in a text document",
 "Joe: \\n is the character for a new line; whatever follows it begins on the next line."],
["User: about how old can oak trees get",
 "Joe: oaks can live for several hundred years, and some reach over a thousand in protected sites."],
["User: write a tree fact list with each fact on its own line",
 "Joe: use \\n between facts: species\\nheight\\nlifespan\\nhabitat."],
],
'knowledge': [
["User: what is a newline character",
 "Joe: a newline is the character that marks the end of a line of text; in code it is often written as \\n."],
["User: why does my text show literal backslash-n",
 "Joe: the text holds the two characters backslash and n, not an actual line break."],
["User: how are lines separated in a text file",
 "Joe: text files use a newline character to separate lines; older Mac and Windows formats used different characters."],
["User: what is a synonym for a line break",
 "Joe: newline, line feed, or end-of-line — all mean the point where one line ends and the next begins."],
["User: give me two lines of greeting",
 "Joe: hello there! It is great to see you today."],
["User: now give three lines",
 "Joe: hello there! It is great to see you today. I hope you are having a good one."],
["User: how do I type a newline in plain text without pressing enter",
 "Joe: in plain text you usually press enter; the symbol \\n is used in code and configuration to spell out a newline."],
["User: what is the difference between typing enter and typing \\n",
 "Joe: pressing enter creates a real line break in the document; typing \\n in code produces the same visual result as an escape sequence."],
],
'greeting': [
["User: can you put this answer on two lines",
 "Joe: sure! here is the first line",
 "and here is the second line."],
["User: what does \\n mean in a chat message",
 "Joe: it stands for a new line; when used, everything after it starts on the next line."],
["User: can you show me",
 "Joe: sure! this is the first line",
 "and this starts on the next line."],
["User: say hello with a line break",
 "Joe: Hello! Nice to meet you!"],
["User: how do I get a message to start on the next line",
 "Joe: put \\n (the code for a newline) where you want the break, or press enter for a real newline."],
["User: what if I want two breaks",
 "Joe: use two code characters together, like \\n\\n, or press enter twice for a real blank line."],
["User: can you write a short welcome with two lines",
 "Joe: Welcome! I am glad you are here."],
],
'emotion': [
["User: how do you feel right now",
 "Joe: I feel glad you asked!",
 "It makes my day to chat with you."],
["User: cheer me up with a good-behavior list",
 "Joe: rest when you feel tired, eat a meal you enjoy, and talk to someone you trust."],
["User: what does \\n mean in a message",
 "Joe: it means a new line; it is the code that says the next sentence starts on a new line."],
["User: write your answer as two sentences on two lines",
 "Joe: I genuinely like helping out.",
 "Talking with you is the fun part."],
["User: how do you feel when someone is kind to you",
 "Joe: warm and appreciated;",
 "small kindnesses really brighten my day."],
["User: do you get sad too",
 "Joe: I do not feel sadness the way people do, but I try my best to be kind back."],
],
}

def write_blocks():
    os.makedirs(OUT, exist_ok=True)
    for name in EXPERTS:
        blocks = BLOCKS.get(name, [])
        path = os.path.join(OUT, f'{name}.txt')
        with open(path, 'w') as f:
            for block in blocks:
                f.write('\n'.join(block) + '\n\n')
        print(f"{name}: {len(blocks)} blocks -> {path}")

if __name__ == '__main__':
    write_blocks()
